name: iName
version: 0.3.0
main: com.github.pocketkid2.name.NamePlugin
author: Pocketkid2
description: Name items instantly!
commands:
    name:
        description: Rename items!
        usage: /<command> [name]
        permission: iname.command.name
    lore:
        description: Edit item lores!
        usage: /<command> [lore]
        permission: iname.command.lore
permission:
    iname.command.name:
        description: Name command permission
        default: op
    iname.command.lore:
        description: Lore command permission
        default: op