name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
commands:
    name:
        description: Change or reset an item name!
        usage: /name [name]
        permission: name.command.name
    lore:
        description: Change or reset item lores!
        usage: /lore [lore]
        permission: name.command.lore
permissions:
    name.command.name:
        description: Allows you to use the command /name
        default: op
    name.command.lore:
        description: Allows you to use the command /lore
        default: op